/**
 * SomaSync — ICS Calendar Generator
 * Generates .ics files and Google Calendar URLs for timetable events.
 */

const TIMEZONE = "Africa/Nairobi";

/**
 * Get the next occurrence of a given weekday from today.
 * @param {string} dayShort - "Mon", "Tue", etc.
 * @returns {Date}
 */
function getNextDay(dayShort) {
  const dayMap = { Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6, Sun: 0 };
  const target = dayMap[dayShort];
  const now = new Date();
  const current = now.getDay();
  let diff = target - current;
  if (diff < 0) diff += 7;
  if (diff === 0) diff = 0; // today
  const result = new Date(now);
  result.setDate(result.getDate() + diff);
  return result;
}

/**
 * Format a date + time string into ICS DTSTART format (YYYYMMDDTHHMMSS).
 */
function toICSDate(date, time) {
  const [h, m] = time.split(":").map(Number);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}${month}${day}T${String(h).padStart(2, "0")}${String(m).padStart(2, "0")}00`;
}

/**
 * Format for Google Calendar URL (YYYYMMDDTHHMMSSZ format in UTC-ish).
 */
function toGCalDate(date, time) {
  const [h, m] = time.split(":").map(Number);
  // EAT is UTC+3, so subtract 3 hours for UTC
  const utcDate = new Date(date);
  utcDate.setHours(h - 3, m, 0, 0);
  const year = utcDate.getFullYear();
  const month = String(utcDate.getMonth() + 1).padStart(2, "0");
  const day = String(utcDate.getDate()).padStart(2, "0");
  const hrs = String(utcDate.getHours()).padStart(2, "0");
  const mins = String(utcDate.getMinutes()).padStart(2, "0");
  return `${year}${month}${day}T${hrs}${mins}00Z`;
}

/**
 * Generate an ICS calendar string for a single event.
 */
export function generateICSEvent(event, dayShort, recurring = false) {
  const date = getNextDay(dayShort);
  const dtStart = toICSDate(date, event.time);
  const dtEnd = event.endTime ? toICSDate(date, event.endTime) : toICSDate(date, event.time);

  const lines = [
    "BEGIN:VEVENT",
    `DTSTART;TZID=${TIMEZONE}:${dtStart}`,
    `DTEND;TZID=${TIMEZONE}:${dtEnd}`,
    `SUMMARY:${escapeICS(event.title)}`,
    `DESCRIPTION:${escapeICS(`Category: ${event.category}${event.notes ? "\\n" + event.notes : ""}\\nGenerated by SomaSync`)}`,
    `UID:${event.id}@somasync.tech`,
    `DTSTAMP:${toICSDate(new Date(), `${new Date().getHours()}:${new Date().getMinutes()}`)}`,
  ];

  if (recurring) {
    const dayMap = { Mon: "MO", Tue: "TU", Wed: "WE", Thu: "TH", Fri: "FR", Sat: "SA", Sun: "SU" };
    lines.push(`RRULE:FREQ=WEEKLY;BYDAY=${dayMap[dayShort]}`);
  }

  lines.push("END:VEVENT");
  return lines.join("\r\n");
}

function escapeICS(text) {
  if (!text) return "";
  return text.replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,").replace(/\n/g, "\\n");
}

/**
 * Generate a full ICS calendar file for all events.
 */
export function generateICSCalendar(allEvents, recurring = false) {
  const lines = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//SomaSync//Study Planner//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:SomaSync Study Planner",
    `X-WR-TIMEZONE:${TIMEZONE}`,
    // Timezone definition
    "BEGIN:VTIMEZONE",
    `TZID:${TIMEZONE}`,
    "BEGIN:STANDARD",
    "DTSTART:19700101T000000",
    "TZOFFSETFROM:+0300",
    "TZOFFSETTO:+0300",
    "END:STANDARD",
    "END:VTIMEZONE",
  ];

  const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
  for (const day of days) {
    const dayEvents = allEvents[day] || [];
    for (const event of dayEvents) {
      lines.push(generateICSEvent(event, day, recurring));
    }
  }

  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

/**
 * Generate a Google Calendar event creation URL.
 */
export function generateGoogleCalendarUrl(event, dayShort) {
  const date = getNextDay(dayShort);
  const start = toGCalDate(date, event.time);
  const end = event.endTime ? toGCalDate(date, event.endTime) : start;

  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: event.title,
    dates: `${start}/${end}`,
    details: `Category: ${event.category}${event.notes ? "\n" + event.notes : ""}\n\nGenerated by SomaSync`,
    location: "Zetech University",
    trp: "true",
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

/**
 * Download an ICS file.
 */
export function downloadICS(icsContent, filename = "somasync-timetable.ics") {
  const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
